/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

//NETBEANS
import javax.swing.JOptionPane;

//PROYECTO
import static Controller.Controlador.*;
import DAO_Controller.DAOSQL;
import Excepcion.DAO_Excep;
import Excepcion.SerExcepcion;
import Model.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class Baja extends javax.swing.JDialog {

    boolean ejecutaUsuario = true;

    /**
     * Creates new form Baja
     */
    public Baja(javax.swing.JFrame parent, boolean modal) throws DAO_Excep {
        
        super(parent, modal);
        
        System.out.println("[OK] Abriendo el JDialog de Baja");
        //Cambiar color de fondo
        getContentPane().setBackground(new Color(0, 24, 78));
        
        setIconImage(new ImageIcon(getClass().getResource("/imgs/inicio.png")).getImage());
        
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        System.out.println("[OK] Componentes inicializados correctamente");
        
        DAOSQL daoBaja = new DAOSQL();
        
        //Por defecto carga los planetas
        for (Planeta planeta : daoBaja.readPlanet()) {
            nombreslista.addItem(planeta.getName());
        }
        String nombre = (String) nombreslista.getSelectedItem();
        Planeta p = getPlanet(new Planeta(nombre));
        info.setText(p.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nombreslista = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        filtro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextPane();
        eliminarButton = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1023, 805));
        setPreferredSize(new java.awt.Dimension(1023, 805));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText(" NOMBRE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        nombreslista.setBackground(new java.awt.Color(45, 45, 45));
        nombreslista.setForeground(new java.awt.Color(255, 255, 0));
        nombreslista.setBorder(null);
        nombreslista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nombreslistaItemStateChanged(evt);
            }
        });
        getContentPane().add(nombreslista, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText(" FILTRO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        filtro.setBackground(new java.awt.Color(45, 45, 45));
        filtro.setForeground(new java.awt.Color(255, 255, 0));
        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planetas", "Ciudadanos" }));
        filtro.setBorder(null);
        filtro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroItemStateChanged(evt);
            }
        });
        getContentPane().add(filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        info.setEditable(false);
        info.setBackground(new java.awt.Color(45, 45, 45));
        info.setBorder(null);
        info.setForeground(new java.awt.Color(255, 255, 0));
        info.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        info.setFocusable(false);
        jScrollPane1.setViewportView(info);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 190, 230));

        eliminarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/eliminarSer 2.jpg"))); // NOI18N
        eliminarButton.setBorder(null);
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 340, 80));

        salir.setBackground(new java.awt.Color(255, 250, 250));
        salir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(51, 51, 51));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salir 2.jpg"))); // NOI18N
        salir.setBorder(null);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 630, -1, 80));

        jLabel9.setBackground(new java.awt.Color(0, 24, 78));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/panel de control copia 2.jpg"))); // NOI18N
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1020, 420));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/deleteBeing.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1023, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        // TODO add your handling code here:   
        DAOSQL daoDelete = new DAOSQL();
        
        int resultadoConfirmacion = JOptionPane.showConfirmDialog(this, "¿Deseas eliminar el ciudadano"
                + " / planeta seleccionado?", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        
        if (resultadoConfirmacion == 0) {
            
            String nombre = (String) nombreslista.getSelectedItem();
            
            //--------------- 
            //PLANETAS
            //--------------- 
            if (filtro.getSelectedItem().equals("Planetas")) {
                
                Planeta p = null;
                try {
                    
                    p = daoDelete.getPlanet(new Planeta(nombre));
                    
                } catch (DAO_Excep ex) {
                    Logger.getLogger(Baja.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {

                    //una vez eliminado, cerraremos la ventana
                    daoDelete.deletePlanet(p);
                    dispose();
                    
                } catch (DAO_Excep ex) {
                    Logger.getLogger(Baja.class.getName()).log(Level.SEVERE, null, ex);
                }
                dispose();
                
            //--------------- 
            //CIUDADANOS
            //--------------- 
            } else if (filtro.getSelectedItem().equals("Ciudadanos")) {
                
                Ser s = null;
                
                try {
                    
                    s = daoDelete.getSer(new Ser(nombre));
                    
                } catch (DAO_Excep ex) {
                    Logger.getLogger(Baja.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    
                    //una vez eliminado, cerraremos la ventana
                    deleteSer(s);
                    dispose();
                    
                } catch (SerExcepcion ex) {
                    Logger.getLogger(Baja.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DAO_Excep ex) {
                    Logger.getLogger(Baja.class.getName()).log(Level.SEVERE, null, ex);
                }
                dispose();
            }
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void filtroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroItemStateChanged
        
        ejecutaUsuario = false;
        nombreslista.removeAllItems();
        
        DAOSQL daoFilter = new DAOSQL();
        
        if (filtro.getSelectedItem().toString().equals("Planetas")) {
            
            try {
                for (Planeta planeta : daoFilter.readPlanet()) {
                    
                    nombreslista.addItem(planeta.getName());
                }
            } catch (DAO_Excep ex) {
                Logger.getLogger(Baja.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            info.setText("");
            
            try {
                info.setText(getPlanet(new Planeta((String)nombreslista.getSelectedItem())).toString());
            } catch (DAO_Excep ex) {
                Logger.getLogger(Baja.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (filtro.getSelectedItem().toString().equals("Ciudadanos")) {
            
            try {
                //for (Planeta planeta : daoFilter.readPlanet()) {
                    
                    for (Ser s : daoFilter.readSer()) {
                        
                        nombreslista.addItem(s.getName());
                    }
                //}
            } catch (DAO_Excep ex) {
                Logger.getLogger(Baja.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            info.setText("");
            
            try {
                
                info.setText(daoFilter.getSer(new Ser((String)nombreslista.getSelectedItem())).toString() +
                        "\n" + daoFilter.getPlanetaSer(new Ser((String)nombreslista.getSelectedItem())));
                
            } catch (DAO_Excep ex) {
                
                Logger.getLogger(Baja.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        ejecutaUsuario = true;
    }//GEN-LAST:event_filtroItemStateChanged

    private void nombreslistaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nombreslistaItemStateChanged
        if (!ejecutaUsuario) {

        } else {
            
            //Agregaremos un "DAOSQL" para buscar la siguiente información:
            //      |
            //      |- Buscar información del Ser (getSer) linea 313
            //      |
            //      |_ Buscar el planeta al que pertenece ese Ser (getPlanetaSer) linea 314
            
            DAOSQL daoFilter = new DAOSQL();
            info.setText("");
            
            if (filtro.getSelectedItem().toString().equals("Planetas")) {
                
                String nombre = nombreslista.getSelectedItem().toString();
                
                try {
                    info.setText(getPlanet(new Planeta(nombre)).toString());
                
                } catch (DAO_Excep ex) {
                    
                    Logger.getLogger(Baja.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (filtro.getSelectedItem().toString().equals("Ciudadanos")) {
                
                String nombre = nombreslista.getSelectedItem().toString();

                try {
                    
                    info.setText(daoFilter.getSer(new Ser(nombre)).toString()+
                            "\n" + daoFilter.getPlanetaSer(new Ser(nombre)));
                    
                } catch (DAO_Excep ex) {
                    
                    Logger.getLogger(Baja.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_nombreslistaItemStateChanged

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    System.out.println("[~] Intentando crear ventana Baja...");
                    Baja dialog = new Baja(new javax.swing.JFrame(), true);
                    System.out.println("[OK] Ventana Baja creada");
                    
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (DAO_Excep ex) {
                    ex.printStackTrace(); // Muestra el error en consola
                    JOptionPane.showMessageDialog(null, "Error al abrir la ventana Baja:\n" + ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminarButton;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JTextPane info;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> nombreslista;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
