package View;

import static Controller.Controlador.*;
import DAO_Controller.DAOSQL;
import Excepcion.DAO_Excep;
import Model.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class BuscarModificar extends javax.swing.JDialog {

    /**
     * Creates new form Modificar
     */
    public BuscarModificar(javax.swing.JFrame parent, boolean modal) throws DAO_Excep {
        super(parent, modal);
        
        //Cambiar color de fondo
        getContentPane().setBackground(new Color(0, 24, 78));
        
        setIconImage(new ImageIcon(getClass().getResource("/imgs/inicio.png")).getImage());
        
        DAOSQL daoBM = new DAOSQL();
        initComponents();
        int count = 0;
        
        for (Ser ser : daoBM.readSer()) {
            System.out.println("[BuscarModificar] Entra " + count);
            nombresserlista.addItem(ser.getName());
            count++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        ModificarHumano = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreciudadano = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nombresserlista = new javax.swing.JComboBox<>();
        buscarciudadano = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        salir1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText(" Nombre: ");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, new java.awt.Color(102, 102, 102)));
        jLabel2.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 10, 10);
        jPanel2.add(jLabel2, gridBagConstraints);

        nombreciudadano.setText(nombresserlista.getName());
        nombreciudadano.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 10, 10);
        jPanel2.add(nombreciudadano, gridBagConstraints);

        ModificarHumano.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1022, 733));
        setPreferredSize(new java.awt.Dimension(1022, 733));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("NOMBRE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        getContentPane().add(nombresserlista, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 100, -1));

        buscarciudadano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/buscar.jpg"))); // NOI18N
        buscarciudadano.setBorder(null);
        buscarciudadano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarciudadanoActionPerformed(evt);
            }
        });
        getContentPane().add(buscarciudadano, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, 80));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/busquedaModificar.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        salir1.setBackground(new java.awt.Color(255, 250, 250));
        salir1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salir1.setForeground(new java.awt.Color(51, 51, 51));
        salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salir 2.jpg"))); // NOI18N
        salir1.setBorder(null);
        salir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });
        getContentPane().add(salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, 80));

        jLabel9.setBackground(new java.awt.Color(0, 24, 78));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/panel planetas.jpg"))); // NOI18N
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 230, 1020, 420));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/final startucom.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 860, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void buscarciudadanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarciudadanoActionPerformed

        DAOSQL daoBM = new DAOSQL();
        System.out.println("[BuscarModificar] daoBM entra");
        
        String nombre = (String) nombresserlista.getSelectedItem();
        
        Ser s = null;
        
        try {
            
            System.out.println("[BuscarModificar] try entra");
            s = daoBM.getSer(new Ser(nombre));
            System.out.println("[BuscarModificar] try 2 entra");
            
            //Comprobaremos que nos devuelve "s"
            if (s == null) {
                System.out.println("[BuscarModificar] getSer develve null");
            } else {
                System.out.println("[BuscarModificar] getSer develve instancia de: " + s.getClass().getName());
            }
            
        } catch (DAO_Excep ex) {
            System.out.println("[BuscarModificar] catch entra");
            Logger.getLogger(BuscarModificar.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.out.println("[BuscarModificar] if casi entra");
        if (s instanceof Vulcaniano) {
            System.out.println("[BuscarModificar] Vulcaniano entra");
            
            ModificarVulcaniano mdfvul = new ModificarVulcaniano(this, true, new Vulcaniano((String) nombresserlista.getSelectedItem()));
            mdfvul.setLocationRelativeTo(null);
            mdfvul.setVisible(true);
            
        } else if (s instanceof Andoriano) {
            System.out.println("[BuscarModificar] Andoriano entra");
            
            ModificarAndoriano mdfan = new ModificarAndoriano(this, true, new Andoriano((String) nombresserlista.getSelectedItem()));
            mdfan.setLocationRelativeTo(null);
            mdfan.setVisible(true);
            
        } else if (s instanceof Klingon) {
            System.out.println("[BuscarModificar] Klingon entra");
            
            ModificarKlingon mdfki = new ModificarKlingon(this, true, new Klingon((String) nombresserlista.getSelectedItem()));
            mdfki.setLocationRelativeTo(null);
            mdfki.setVisible(true);
            
        } else if (s instanceof Nibiriano) {
            System.out.println("[BuscarModificar] Nibiriano entra");
            
            ModificarNibiriano mdfnib = new ModificarNibiriano(this, true, new Nibiriano((String) nombresserlista.getSelectedItem()));
            mdfnib.setLocationRelativeTo(null);
            mdfnib.setVisible(true);
            
        } else if (s instanceof Ferengi) {
            System.out.println("[BuscarModificar] Ferengi entra");

            ModificarFerengi mdffe = new ModificarFerengi(this, true, new Ferengi((String) nombresserlista.getSelectedItem()));
            mdffe.setLocationRelativeTo(null);
            mdffe.setVisible(true);
            
        } else if (s instanceof Humano) {
            System.out.println("[BuscarModificar] Humano entra");
            
            ModificarHumano modificarhumano = null;
            
            try {
                modificarhumano = new ModificarHumano(this, true, new Humano((String) nombresserlista.getSelectedItem()));
            } catch (DAO_Excep ex) {
                Logger.getLogger(BuscarModificar.class.getName()).log(Level.SEVERE, null, ex);
            }
            modificarhumano.setLocationRelativeTo(null);
            modificarhumano.setVisible(true);
        }
        System.out.println("[BuscarModificar] salida");
    }//GEN-LAST:event_buscarciudadanoActionPerformed

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarModificar dialog = null;
                try {
                    dialog = new BuscarModificar(new javax.swing.JFrame(), true);
                } catch (DAO_Excep ex) {
                    Logger.getLogger(BuscarModificar.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ModificarHumano;
    private javax.swing.JButton buscarciudadano;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreciudadano;
    private javax.swing.JComboBox<String> nombresserlista;
    private javax.swing.JButton salir1;
    // End of variables declaration//GEN-END:variables
}
