package View;

import java.awt.Color;
import javax.swing.ImageIcon;

public class CrearCiudadano extends javax.swing.JDialog {

    public CrearCiudadano(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        
        System.out.println("[OK] Abriendo el JDialog de CrearCiudadano");
        //Cambiar color de fondo
        getContentPane().setBackground(new Color(0, 24, 78));
        
        setIconImage(new ImageIcon(getClass().getResource("/imgs/inicio.png")).getImage());
        
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        System.out.println("[OK] Componentes inicializados correctamente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        crearhumano = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        crearnibiriano = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        crearvulcaniano = new javax.swing.JButton();
        crearandoriano = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        crearklingon = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        crearferengi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1022, 733));
        setPreferredSize(new java.awt.Dimension(1022, 733));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir1.setBackground(new java.awt.Color(255, 250, 250));
        salir1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salir1.setForeground(new java.awt.Color(51, 51, 51));
        salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salir 2.jpg"))); // NOI18N
        salir1.setBorder(null);
        salir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });
        getContentPane().add(salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, -1, 80));

        jPanel1.setBackground(new java.awt.Color(0, 24, 78));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/humano.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        crearhumano.setBackground(new java.awt.Color(255, 250, 250));
        crearhumano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/name1.jpg"))); // NOI18N
        crearhumano.setBorder(null);
        crearhumano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearhumano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearhumanoActionPerformed(evt);
            }
        });
        jPanel1.add(crearhumano, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 96, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/nibiriano.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 80, -1));

        crearnibiriano.setBackground(new java.awt.Color(255, 250, 250));
        crearnibiriano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/name2.jpg"))); // NOI18N
        crearnibiriano.setBorder(null);
        crearnibiriano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearnibiriano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearnibirianoActionPerformed(evt);
            }
        });
        jPanel1.add(crearnibiriano, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/vulcaniano100.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        crearvulcaniano.setBackground(new java.awt.Color(255, 250, 250));
        crearvulcaniano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/name3.jpg"))); // NOI18N
        crearvulcaniano.setBorder(null);
        crearvulcaniano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearvulcaniano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearvulcanianoActionPerformed(evt);
            }
        });
        jPanel1.add(crearvulcaniano, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 80));

        crearandoriano.setBackground(new java.awt.Color(255, 250, 250));
        crearandoriano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/name4.jpg"))); // NOI18N
        crearandoriano.setBorder(null);
        crearandoriano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearandoriano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearandorianoActionPerformed(evt);
            }
        });
        jPanel1.add(crearandoriano, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/andoriano.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 90));

        crearklingon.setBackground(new java.awt.Color(255, 250, 250));
        crearklingon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/name5.jpg"))); // NOI18N
        crearklingon.setBorder(null);
        crearklingon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearklingon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearklingonActionPerformed(evt);
            }
        });
        jPanel1.add(crearklingon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/klingon100.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 90));

        crearferengi.setBackground(new java.awt.Color(255, 250, 250));
        crearferengi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/name6.jpg"))); // NOI18N
        crearferengi.setBorder(null);
        crearferengi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearferengi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearferengiActionPerformed(evt);
            }
        });
        jPanel1.add(crearferengi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ferengi100.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 390, 380));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/createBeingTitle.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //===============================================================================================//
    //||                                                                                           ||//
    //===============================================================================================//
    /**
     * Un boton para abrir la ventana crear Humano
     *
     * @param evt
     */
    private void crearhumanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearhumanoActionPerformed
        CrearHumano crearhumano = new CrearHumano(this, true);
        crearhumano.setLocationRelativeTo(null);
        crearhumano.setVisible(true);
    }//GEN-LAST:event_crearhumanoActionPerformed

    /**
     * Boton para abrir la ventana crear Andoriano
     *
     * @param evt
     */
    private void crearandorianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearandorianoActionPerformed
        CrearAndoriano crearandoriano = new CrearAndoriano(this, true);
        crearandoriano.setLocationRelativeTo(null);
        crearandoriano.setVisible(true);
    }//GEN-LAST:event_crearandorianoActionPerformed

    /**
     * Boton para abrir la ventana crear Ferengi
     *
     * @param evt
     */
    private void crearferengiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearferengiActionPerformed
        CrearFerengi crearferengi = new CrearFerengi(this, true);
        crearferengi.setLocationRelativeTo(null);
        crearferengi.setVisible(true);
    }//GEN-LAST:event_crearferengiActionPerformed

    /**
     * Boton para abrir la ventana crear Klingon
     *
     * @param evt
     */
    private void crearklingonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearklingonActionPerformed
        CrearKlingon crearklingon = new CrearKlingon(this, true);
        crearklingon.setLocationRelativeTo(null);
        crearklingon.setVisible(true);
    }//GEN-LAST:event_crearklingonActionPerformed

    /**
     * Boton para abrir la ventena crear Nibiriano
     *
     * @param evt
     */
    private void crearnibirianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearnibirianoActionPerformed
        CrearNibiriano crearnibiriano = new CrearNibiriano(this, true);
        crearnibiriano.setLocationRelativeTo(null);
        crearnibiriano.setVisible(true);
    }//GEN-LAST:event_crearnibirianoActionPerformed

    /**
     * Boton para abrir la ventana crear Vulcaniano
     *
     * @param evt
     */
    private void crearvulcanianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearvulcanianoActionPerformed
        CrearVulcaniano crearvulcaniano = new CrearVulcaniano(this, true);
        crearvulcaniano.setLocationRelativeTo(null);
        crearvulcaniano.setVisible(true);
    }//GEN-LAST:event_crearvulcanianoActionPerformed

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salir1ActionPerformed

    //===============================================================================================//
    //||                                                                                           ||//
    //===============================================================================================//
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCiudadano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCiudadano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCiudadano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCiudadano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearCiudadano dialog = new CrearCiudadano(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearandoriano;
    private javax.swing.JButton crearferengi;
    private javax.swing.JButton crearhumano;
    private javax.swing.JButton crearklingon;
    private javax.swing.JButton crearnibiriano;
    private javax.swing.JButton crearvulcaniano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salir1;
    // End of variables declaration//GEN-END:variables
}
