package View;


//NETBEANS
import javax.swing.JOptionPane;

//PROYECTO
import static Controller.Controlador.*;
import DAO_Controller.DAOSQL;
import Excepcion.DAO_Excep;
import Excepcion.SerExcepcion;
import Model.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

public class CrearFerengi extends javax.swing.JDialog {

    /**
     * Crear clase CrearFerengi
     *
     * @param parent
     * @param modal
     */
    public CrearFerengi(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Cambiar color de fondo
        getContentPane().setBackground(new Color(0, 24, 78));
        
        setIconImage(new ImageIcon(getClass().getResource("/imgs/inicio.png")).getImage());

        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearhumano = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreciudadano = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombreplaneta = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        oro = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        salir1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 750));
        setPreferredSize(new java.awt.Dimension(1020, 750));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearhumano.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        crearhumano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/guardar2.jpg"))); // NOI18N
        crearhumano.setBorder(null);
        crearhumano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearhumano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearhumanoActionPerformed(evt);
            }
        });
        getContentPane().add(crearhumano, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 340, 80));

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("NOMBRE:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 70, 30));
        jPanel1.add(nombreciudadano, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 84, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("RESIDE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 60, 30));

        jPanel1.add(nombreplaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 100, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("ORO KG:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 70, 30));

        oro.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(oro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 84, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 311, 490, 200));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/createFer.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        salir1.setBackground(new java.awt.Color(255, 250, 250));
        salir1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salir1.setForeground(new java.awt.Color(51, 51, 51));
        salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salir 2.jpg"))); // NOI18N
        salir1.setBorder(null);
        salir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });
        getContentPane().add(salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 630, -1, 80));

        jLabel9.setBackground(new java.awt.Color(0, 24, 78));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/panel de control.jpg"))); // NOI18N
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1020, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //===============================================================================================//
    //||                                                                                           ||//
    //===============================================================================================//
    /**
     * Esta funcion es el boton y sirve para crear el ciudadano
     *
     * @param evt
     */
    private void crearhumanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearhumanoActionPerformed
        String name = nombreciudadano.getText();
        int caoro = (int) oro.getValue();
        String planeta = (String) nombreplaneta.getSelectedItem();

        //Creacion de objeto Planeta y Ser
        Planeta p = null;
        try {
            p = getPlanet(new Planeta(planeta));
        } catch (DAO_Excep ex) {
            Logger.getLogger(CrearFerengi.class.getName()).log(Level.SEVERE, null, ex);
        }
        Ser s = new Ferengi(caoro, name);

        if (!(name.isEmpty())) {
            //Si el nombre es más pequeño o igual a 3 muestra el siguiente mensaje
            if (name.length() <= 3) {
                JOptionPane.showMessageDialog(this, "La longitud del nombre"
                        + " no es correcto (4)",
                        "Nombre incorrecto", JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    
                    //Instancia que usaremos para verificar duplicados
                    DAOSQL dao = new DAOSQL();
                    
                    try {
                    Ser existente = dao.getSer(new Ser(name));

                    if (existente != null) {
                        JOptionPane.showMessageDialog(this,
                            "Ya existe un ser con ese nombre. No se permiten duplicados.",
                            "Duplicado",
                            JOptionPane.ERROR_MESSAGE);
                        return;
                        }
                    } catch (DAO_Excep ex) {
                        //Si lanza excepción porque NO existe el ser, continuamos como normal
                    }
                    
                    //Llama la funcion createser y añado los objetos
                    createser(s, p);
                    JOptionPane.showMessageDialog(this, "Se ha registrado correctamente el ciudadano",
                            "Ciudadano Registrado", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                } catch (SerExcepcion ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(),
                            "Ciudadano No Registrado", JOptionPane.ERROR_MESSAGE);
                    
                //pondremos este catch de aquí abajo parta poder controlar la excepción de DAO_Excep
                } catch (DAO_Excep ex) {
                    Logger.getLogger(CrearFerengi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            //Si el nombre esta vacio muestra el siguiente mensaje
            JOptionPane.showMessageDialog(this, "No se permite campos vacios",
                    "Datos vacios", JOptionPane.WARNING_MESSAGE
            );
        }


    }//GEN-LAST:event_crearhumanoActionPerformed
    //===============================================================================================//
    //||                                                                                           ||//
    //===============================================================================================//


    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
        //Pondremos daoCrearH aquí debajo, ya que super requiere estar la primera
        //de las líneas. Sino lo marcará como mal
        DAOSQL daoCrearF = new DAOSQL();
        
        nombreplaneta.removeAllItems();
        try {
            for (Planeta p : daoCrearF.readPlanet()) {
                nombreplaneta.addItem(p.getName());
            }
        } catch (DAO_Excep ex) {
            Logger.getLogger(CrearFerengi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearFerengi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearFerengi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearFerengi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearFerengi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearFerengi dialog = new CrearFerengi(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearhumano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreciudadano;
    private javax.swing.JComboBox<String> nombreplaneta;
    private javax.swing.JSpinner oro;
    private javax.swing.JButton salir1;
    // End of variables declaration//GEN-END:variables
}
