package View;

//NETBEANS
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

//PROYECTO
import Model.Planeta;
import Excepcion.PlanetaExcepcion;
import static Controller.Controlador.*;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class CrearPlaneta extends javax.swing.JDialog {

    /**
     * Creates new form CrearPlaneta
     */
    public CrearPlaneta(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        
        System.out.println("[OK] Abriendo el JDialog de CrearPlaneta");
        //Cambiar color de fondo
        getContentPane().setBackground(new Color(0, 24, 78));
                
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imgs/inicio.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        System.out.println("[OK] Componentes inicializados correctamente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreplaneta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombregalaxia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        poblacionmaxima = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        clima = new javax.swing.JComboBox<>();
        aquatic = new javax.swing.JCheckBox();
        flora = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        crearplaneta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 600));
        setPreferredSize(new java.awt.Dimension(1022, 710));
        setSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(203, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText(" Planeta: ");
        jLabel1.setFocusable(false);
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 90, 25));

        nombreplaneta.setBackground(new java.awt.Color(255, 250, 250));
        nombreplaneta.setPreferredSize(new java.awt.Dimension(73, 22));
        getContentPane().add(nombreplaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 130, 27));

        jLabel2.setBackground(new java.awt.Color(203, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText(" Galaxia: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, 30));

        nombregalaxia.setBackground(new java.awt.Color(255, 250, 250));
        nombregalaxia.setPreferredSize(new java.awt.Dimension(73, 22));
        getContentPane().add(nombregalaxia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 130, 27));

        jLabel3.setBackground(new java.awt.Color(203, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText(" Poblacion : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, 30));

        poblacionmaxima.setModel(new javax.swing.SpinnerNumberModel(1, 0, 1000, 1));
        poblacionmaxima.setEditor(new javax.swing.JSpinner.NumberEditor(poblacionmaxima, ""));
        getContentPane().add(poblacionmaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 129, 27));

        jLabel4.setBackground(new java.awt.Color(203, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Clima: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, 30));

        jLabel6.setBackground(new java.awt.Color(203, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Fauna marina: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, 30));

        clima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calido", "Frio", "Templado" }));
        getContentPane().add(clima, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, 30));
        getContentPane().add(aquatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, 30));

        flora.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(flora, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, 30));

        jLabel5.setBackground(new java.awt.Color(203, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Flora: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, 30));

        salir.setBackground(new java.awt.Color(255, 250, 250));
        salir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(51, 51, 51));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salir 2.jpg"))); // NOI18N
        salir.setBorder(null);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        crearplaneta.setBackground(new java.awt.Color(0, 24, 78));
        crearplaneta.setForeground(new java.awt.Color(51, 51, 51));
        crearplaneta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/crearPlaneta 2.jpg"))); // NOI18N
        crearplaneta.setBorder(null);
        crearplaneta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearplaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearplanetaActionPerformed(evt);
            }
        });
        getContentPane().add(crearplaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/createPlanetTitle.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1023, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/final startucom.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 860, 60));

        jLabel9.setBackground(new java.awt.Color(0, 24, 78));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/panel planetas.jpg"))); // NOI18N
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 230, 1020, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botom para crear planeta
     *
     * @param evt
     */
    private void crearplanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearplanetaActionPerformed
        // TODO add your handling code here:
        //Variables de las propiedades de planeta
        String nameplanet = nombreplaneta.getText();
        String namegalaxy = nombregalaxia.getText();
        int maxpopulation = (int) poblacionmaxima.getValue();
        String weather = (String) clima.getSelectedItem();
        boolean floraa = flora.isSelected();
        boolean aquaticc = aquatic.isSelected();

        if (!(nameplanet.isEmpty() || namegalaxy.isEmpty())) {
            if (nameplanet.length() <= 3 && namegalaxy.length() <= 3) {
                JOptionPane.showMessageDialog(this, "La longitud del nombre de la galaxia y nombre"
                    + "del planeta no son  correctos (4)",
                    "Nombres incorrectos", JOptionPane.WARNING_MESSAGE);
            } else if (nameplanet.length() <= 3) {
                JOptionPane.showMessageDialog(this, "La longitud del nombre del planeta no es correcto (4)",
                    "Nombre planeta incorrecto", JOptionPane.WARNING_MESSAGE);
            } else if (namegalaxy.length() <= 3) {
                JOptionPane.showMessageDialog(this, "La longitud del nombre de la galaxia no es correcto (4)",
                    "Nombre galaxia incorrecto", JOptionPane.WARNING_MESSAGE);
            } else if (maxpopulation < 0) {
                JOptionPane.showMessageDialog(this, "No se puede introducir numeros negativos",
                    "Numeros negativos", JOptionPane.WARNING_MESSAGE);
            } else {
                Planeta p = new Planeta(nameplanet, namegalaxy, maxpopulation, weather, floraa, aquaticc);
                try {
                    createplanet(p);
                    JOptionPane.showMessageDialog(this, "Se ha registrado correctamente el planeta",
                        "Planeta Registrado", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                } catch (PlanetaExcepcion ex) {
                    nombreplaneta.setText("");
                    JOptionPane.showMessageDialog(this, ex.getMessage(),
                        "Planeta No Registrado", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se puede dejar campos en blanco", "Datos vacíos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_crearplanetaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPlaneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPlaneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPlaneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPlaneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearPlaneta dialog = new CrearPlaneta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aquatic;
    private javax.swing.JComboBox<String> clima;
    private javax.swing.JButton crearplaneta;
    private javax.swing.JCheckBox flora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombregalaxia;
    private javax.swing.JTextField nombreplaneta;
    private javax.swing.JSpinner poblacionmaxima;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
