package View;

//NETBEANS
import javax.swing.JOptionPane;

//PROYECTO
import static Controller.Controlador.*;
import DAO_Controller.DAOSQL;
import Excepcion.DAO_Excep;
import Model.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

public class ModificarHumano extends javax.swing.JDialog {

    /**
     * Crear clase CrearHumano
     *
     * @param parent
     * @param modal
     */
    public ModificarHumano(javax.swing.JDialog parent, boolean modal, Humano c) throws DAO_Excep {
        super(parent, modal);
        System.out.println("[ModificarHumano] entra");

        //Cambiar color de fondo
        getContentPane().setBackground(new Color(0, 24, 78));
        
        setIconImage(new ImageIcon(getClass().getResource("/imgs/inicio.png")).getImage());

        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        nombreciudadano.setText(c.getName());
        nombreciudadano.setEnabled(false);
        nombreplaneta.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modificarhumano = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        edadhumano = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        nombreplaneta = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        nombreciudadano = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        generohumano = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        salir1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 750));
        setPreferredSize(new java.awt.Dimension(1020, 750));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificarhumano.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modificarhumano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/modificar.jpg"))); // NOI18N
        modificarhumano.setBorder(null);
        modificarhumano.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modificarhumano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarhumanoActionPerformed(evt);
            }
        });
        getContentPane().add(modificarhumano, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 340, 80));

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("EDAD:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, 30));

        edadhumano.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(edadhumano, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 84, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("RESIDE: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 65, 30));

        jPanel1.add(nombreplaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 109, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("NOMBRE: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, 30));

        nombreciudadano.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(nombreciudadano, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 84, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("GENERO: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 65, 30));

        generohumano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jPanel1.add(generohumano, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 109, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 301, 500, 220));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/modificarHum.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        salir1.setBackground(new java.awt.Color(255, 250, 250));
        salir1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salir1.setForeground(new java.awt.Color(51, 51, 51));
        salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salir 2.jpg"))); // NOI18N
        salir1.setBorder(null);
        salir1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });
        getContentPane().add(salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 630, -1, 80));

        jLabel9.setBackground(new java.awt.Color(0, 24, 78));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/panel de control.jpg"))); // NOI18N
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1020, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //===============================================================================================//
    //||                                                                                           ||//
    //===============================================================================================//
    /**
     * Esta funcion es el boton y sirve para modificar el ciudadano
     *
     * @param evt
     */
    private void modificarhumanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarhumanoActionPerformed
        
        DAOSQL daoCH = new DAOSQL();

        String name = nombreciudadano.getText();

        //Variable a modificar
        String newGenero = (String) generohumano.getSelectedItem();
        int newEdad = (int) edadhumano.getValue();

        Ser s = null;
        
        try {
            
            s = daoCH.getSer(new Ser(name));
            
            // Verificaremos si "s" es null
            if (s == null) {
                throw new Exception("[ERROR][X] No se encontro el ser con ese nombre " + name);
            }
            
        } catch (DAO_Excep ex) {
            Logger.getLogger(ModificarHumano.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ModificarHumano.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Verificaremos que el objeto s sea Humano
        if (s != null && s instanceof Humano) {
          
            try {
                
                //Actualizamos
                daoCH.updateHumano(name, newEdad, newGenero);
            
            } catch (DAO_Excep ex) {
                
                Logger.getLogger(ModificarFerengi.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(this, "Se ha modificado correctamente el ciudadano",
                    "Ciudadano Modificado", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        
        } else {
            JOptionPane.showMessageDialog(this, "[ERROR][X] No se encontro el ser con ese nombre", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modificarhumanoActionPerformed

    /**
     * Este evento es cuando la ventana se abre
     *
     * @param evt
     */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
        DAOSQL daoCH = new DAOSQL();
        
        nombreplaneta.removeAllItems();
        
        try {
            
            for (Planeta p : daoCH.readPlanet()) {
                
                nombreplaneta.addItem(p.getName());
            }
            
        } catch (DAO_Excep ex) {
            Logger.getLogger(ModificarAndoriano.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        Ser s = null;
//        
//        try {
//            
//            s = daoCH.getSer(new Ser(nombreciudadano.getText()));
//            
//        } catch (DAO_Excep ex) {
//            Logger.getLogger(ModificarHumano.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        Humano sh = (Humano) s;
//        Planeta p = null;
//
//        try {
//            for (Ser sp : daoCH.readSer()) {
//                if (daoCH.readPlanet().equals(sh.getPlanet())) {
//                    nombreplaneta.addItem(p.getName());
//                    System.out.println(p.getName());
//                }
//            }
//        } catch (DAO_Excep ex) {
//            Logger.getLogger(ModificarHumano.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salir1ActionPerformed

    //===============================================================================================//
    //||                                                                                           ||//
    //===============================================================================================//
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ModificarHumano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ModificarHumano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ModificarHumano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ModificarHumano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ModificarHumano dialog = new ModificarHumano(new javax.swing.JDialog(), true, Humano h);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner edadhumano;
    private javax.swing.JComboBox<String> generohumano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarhumano;
    private javax.swing.JTextField nombreciudadano;
    private javax.swing.JComboBox<String> nombreplaneta;
    private javax.swing.JButton salir1;
    // End of variables declaration//GEN-END:variables
}
