/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

//NETBEANS
import javax.swing.JOptionPane;

//PROYECTO
import static Controller.Controlador.*;
import DAO_Controller.DAOSQL;
import Excepcion.DAO_Excep;
import Model.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class ModificarAndoriano extends javax.swing.JDialog {

    /**
     * Creates new form CrearAndoriano
     */
    public ModificarAndoriano(javax.swing.JDialog parent, boolean modal, Andoriano c) {
        super(parent, modal);
        initComponents();
        //Cambiar color de fondo
        getContentPane().setBackground(new Color(0, 24, 78));
        
        setIconImage(new ImageIcon(getClass().getResource("/imgs/inicio.png")).getImage());

        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearandoriano = new javax.swing.JButton();
        salir1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreciudadano = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        aenar = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        rango = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nombreplaneta = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 750));
        setPreferredSize(new java.awt.Dimension(1020, 750));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearandoriano.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        crearandoriano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/modificar.jpg"))); // NOI18N
        crearandoriano.setBorder(null);
        crearandoriano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearandorianoActionPerformed(evt);
            }
        });
        getContentPane().add(crearandoriano, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, -1, 80));

        salir1.setBackground(new java.awt.Color(255, 250, 250));
        salir1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salir1.setForeground(new java.awt.Color(51, 51, 51));
        salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salir 2.jpg"))); // NOI18N
        salir1.setBorder(null);
        salir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });
        getContentPane().add(salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 630, -1, 80));

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("NOMBRE:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 76, 29));

        nombreciudadano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreciudadanoActionPerformed(evt);
            }
        });
        jPanel1.add(nombreciudadano, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 112, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("AENAR: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 69, 29));

        aenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aenarActionPerformed(evt);
            }
        });
        jPanel1.add(aenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("RANGO: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 76, 29));

        rango.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrenador", "Defensor", "Luchador", "Caballero" }));
        jPanel1.add(rango, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 112, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("RESIDE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 69, 30));

        nombreplaneta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(nombreplaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 92, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 499, 220));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/modificarAnd.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        jLabel9.setBackground(new java.awt.Color(0, 24, 78));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/panel de control.jpg"))); // NOI18N
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1020, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //===============================================================================================//
    //||                                                                                           ||//
    //===============================================================================================//
    /**
     * Esta funcion es el boton y sirve para crear el ciudadano
     *
     * @param evt
     */
    private void crearandorianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearandorianoActionPerformed
        
        DAOSQL daoCA = new DAOSQL();

        //Variables de la propiedades Andoriano
        String name = nombreciudadano.getText();

        //Variables que se cambian
        String valorRango = (String) rango.getSelectedItem();
        boolean liveice = aenar.isSelected();

        //Inicializamos
        Ser s = null;
        
        try {
            //obtendremos el nombre del ser
            s = daoCA.getSer(new Ser(name));
            
        } catch (DAO_Excep ex) {
            Logger.getLogger(ModificarAndoriano.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Creamos una variable Andoriano sh que equivale a Humano s
        Andoriano sa = (Andoriano) s;
        
        //Actualizamos la informacion
        sa.setIceAtThePoles(liveice);
        sa.setRango(valorRango);
        
        JOptionPane.showMessageDialog(this, "Se ha modificado correctamente el ciudadano",
                "Ciudadano Modificado", JOptionPane.INFORMATION_MESSAGE);
        
        dispose();
    }//GEN-LAST:event_crearandorianoActionPerformed

    /**
     * Si la ventana gana focus ejecuta el siguiente codigo
     *
     * @param evt
     */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
        DAOSQL daoCA = new DAOSQL();
        
        nombreplaneta.removeAllItems();
        
        try {
            
            for (Planeta p : daoCA.readPlanet()) {
                
                nombreplaneta.addItem(p.getName());
            }
            
        } catch (DAO_Excep ex) {
            Logger.getLogger(ModificarAndoriano.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void nombreciudadanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreciudadanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreciudadanoActionPerformed

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salir1ActionPerformed

    private void aenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aenarActionPerformed
    //===============================================================================================//
    //||                                                                                           ||//
    //===============================================================================================//
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ModificarAndoriano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ModificarAndoriano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ModificarAndoriano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ModificarAndoriano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ModificarAndoriano dialog = new ModificarAndoriano(new javax.swing.JDialog(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aenar;
    private javax.swing.JButton crearandoriano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreciudadano;
    private javax.swing.JComboBox<String> nombreplaneta;
    private javax.swing.JComboBox<String> rango;
    private javax.swing.JButton salir1;
    // End of variables declaration//GEN-END:variables
}
